### ISSUE TITLE
CircuitBreaker

### ISSUE THREAD

**Issue by hispres** [hispres/winterone#10]
Payment/src/main/java/winterschoolone/Payment.java
```java
@PostPersist
    public void onPostPersist(){
        Payed payed = new Payed();
        BeanUtils.copyProperties(this, payed);
        payed.publishAfterCommit();
        
        try {
                Thread.currentThread().sleep((long) (400 + Math.random() * 220));
        } catch (InterruptedException e) {
                e.printStackTrace();
        }
    }
```
winterone/SirenOrder/src/main/resources/application.yml
```yml
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610
api:
  url:
    Payment: ${configurl}
```

![CircucitBreaker증적](https://user-images.githubusercontent.com/77368578/107917672-a8fa5180-6fab-11eb-9864-69af16a94e5e.png)
