### ISSUE TITLE
ConfigMap

### ISSUE THREAD

**Issue by hispres** [hispres/winterone#11]
winterone/SirenOrder/src/main/resources/application.yml
```yml
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610
api:
  url:
    Payment: ${configurl}
```
winterone/SirenOrder/src/main/java/winterschoolone/external/PaymentService.java
```java
@FeignClient(name="Payment", url="${api.url.Payment}")
public interface PaymentService {

    @RequestMapping(method= RequestMethod.POST, path="/payments")
    public void pay(@RequestBody Payment payment);

}
```
![ConfigMap 설정 실행](https://user-images.githubusercontent.com/77368578/107917722-b9123100-6fab-11eb-978b-885520bf3db7.png)
![ConfigMap](https://user-images.githubusercontent.com/77368578/107917727-bb748b00-6fab-11eb-8138-fa8f88a11e4e.png)
